// Daftar contoh sekolah di Blitar (Kota & Kabupaten).
// Ini adalah starter list — silakan tambah/kurangi sesuai kebutuhan nyata.
export const blitarSchools: string[] = [
  'SDN Kepanjenkidul 1 Blitar',
  'SDN Sananwetan 1 Blitar',
  'SDN Sukorejo 1 Blitar',
  'SMPN 1 Blitar',
  'SMPN 2 Blitar',
  'SMPN 3 Blitar',
  'SMPN 4 Blitar',
  'SMPN 1 Kademangan',
  'SMPN 1 Garum',
  'SMPN 1 Wlingi',
  'SMPN 1 Srengat',
  'SMAN 1 Blitar',
  'SMAN 2 Blitar',
  'SMAN 3 Blitar',
  'SMAN 4 Blitar',
  'SMAN 1 Kademangan',
  'SMAN 1 Garum',
  'SMAN 1 Wlingi',
  'SMAN 1 Srengat',
  'SMKN 1 Blitar',
  'SMKN 2 Blitar',
  'SMKN 3 Blitar',
  'MAN 1 Kota Blitar',
  'MAN 2 Kota Blitar',
  'MTsN 1 Kota Blitar',
  'MTsN 2 Kota Blitar',
];